### ISSUE TITLE
Pin Sheet Redesign

### ISSUE THREAD

**Issue by superfuturefunk** [foodisready/cooking#13]

**Comment by superfuturefunk** [comment]
![Image](https://github.com/user-attachments/assets/dc26dfd1-4964-42fd-8cc2-2114a514e285)

**Comment by superfuturefunk** [comment]
Pin sheet

- A place for users to quickly gather the items they want

Features?
1. checkmark individual items to save or share 
2. a quick share button at the top to share entire sheet

**Comment by foodisready** [comment]
done
