### ISSUE TITLE
Search Menu Filtering

### ISSUE THREAD

**Issue by superfuturefunk** [foodisready/cooking#8]
- [ ] User search title appears first
- [ ] Associated pills will appear on the bottom

**Comment by superfuturefunk** [comment]
![Image](https://github.com/user-attachments/assets/fe86e8e6-025e-4034-8be9-55561248ad53)
![Image](https://github.com/user-attachments/assets/c21dbc0f-8fd1-4f13-9c38-898d8117bca4)

**Comment by foodisready** [comment]
done
